<script>
var countdownElement = document.getElementById('countdown');
var countdownValue = 2;

function startCountdown() {
    countdownElement.textContent = 'Redirecting to your Task List in ' + countdownValue + ' ...';
    
    if (countdownValue > 1) {
        setTimeout(startCountdown, 1000);
        countdownValue--;
    } else {
        function redirect() {
            window.location.href = "<?= $url ?>/showList";
        }
        setTimeout(redirect, 1000);
    }
}

startCountdown();
</script>